version: '3.8'

services:
  database:
    image: postgres
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=testDB
      - POSTGRES_USER=testUser
      - POSTGRES_PASSWORD=q1w2e3
    networks:
      - hakhak-network
  redis:
    image: redis
    container_name: hakhak-comunity-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - hakhak-network

volumes:
  database: {}
  redis: {}
networks:
  hakhak-network:
