version: '3.8'

services:
  database:
    container_name: hakhak-comunity-db
    build:
      context: .
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - hakhak-network
  redis:
    image: redis
    container_name: hakhak-comunity-redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./redis:/data
    networks:
      - hakhak-network

volumes:
  database: {}
  redis: {}
networks:
  hakhak-network:
