export const META_DATA = {
  KEY: {
    ROLES: 'ROLES',
    MODEL: 'CHECK_MODEL_OF/MODEL',
    CHECK_TYPE: 'CHECK_MODEL_OF/CHECK_TYPE',
    ARGUMENT_ID_NAME: 'CHECK_MODEL_OF/ARGUMENT_ID_NAME',
    CHECK_ID_NAME: 'CHECK_MODEL_OF/CHECK_ID_NAME',
  },
  VALUE: {
    ANY: 'ANY',
  },
} as const;
